version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: mailroom.log
loggers:
  # in order for a logger to show up with __name__,
  # needs to have same name as the object you are logging
  # from, in this case mailroom.model
  mailroom.model:
    level: DEBUG
    handlers: [logfile]
    propagate: no
  #mailroom.modelDB
root:
  level: DEBUG
  handlers: [console]
