print('+', '- ' * 4, end = '')
print('+', '- ' * 4, end = '',)
print('+')
for i in range(4):
    print('|', '  ' * 4, end = '')
    print('|', '  ' * 4, end = '')
    print('|')
print('+', '- ' * 4, end = '')
print('+', '- ' * 4, end = '',)
print('+')
for i in range(4):
    print('|', '  ' * 4, end = '')
    print('|', '  ' * 4, end = '')
    print('|')
print('+', '- ' * 4, end = '')
print('+', '- ' * 4, end = '',)
print('+')
