# Generated by Django 2.0.3 on 2018-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('formula', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('criteria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('rules', models.ManyToManyField(to='exchange.Rule')),
            ],
        ),
    ]
